# 02. Numpy

작성자 : 김정훈 <br>
수정  : 한기영

#### 주의 : 넘파이의 모든 것을 다루지 않습니다. Machine Learning 또는 Deep Learning을 공부하기 위해 최소한 알아야 하는 범위만을 다룹니다.

### 넘파이 실습시간!

Numpy는 데이터 과학을 위한 핵심 라이브러리입니다.
고성능 다차원 배열과 배열 연산을 위한 유용한 도구를 제공합니다

#### 선행지식
1. Python 언어 기초.
2. 행렬에 대한 이해와 약간의 수학적 지식.

#### 실습목표
1. numpy를 이용하여 다양한 모양(shape)의 행렬 array를 만들 수 있습니다. 
2. numpy를 이용하여 다양한 행렬 연산을 수행할 수 있습니다. 
3. 2-d 어레이(혹은 그 이상)를 만들기. 
4. 1-d array를 2-d array로 만들기. 
5. 행렬 간의 곱셈.
6. csv파일 읽기. 
7. numpy array를 python list로 변환, python list를 numpy array로 변환
8. array shuffle, split, sampling (복원/비복원 둘 다.)


### 1. 라이브러리 불러오기

numpy로 파일을 직접 부르기 보다는 
pandas로 불러서 처리하고 필요시 numpy넘겨서 처리

그러므로 numpy로 파일을 부르는 부분은 간단히 다룹니다

In [ ]:
import numpy as np
data = np.genfromtxt("Graduate_apply.csv", delimiter=",", names=True)
print(type(data))
print(data.shape)

In [ ]:
import numpy
data1 = numpy.genfromtxt("Graduate_apply.csv", delimiter=",", names=True)
print(type(data1))
print(data1.shape)

In [ ]:
from numpy import genfromtxt as ggg
data2 = ggg("./Graduate_apply.csv", delimiter=",", names=True)
print(type(data2))
print(data2.shape)

In [ ]:
data2.dtype

In [ ]:
# 어떻게 로딩되었는지 눈으로 한 번 보자!
data2

In [ ]:
# 유용한 라이브러리
import time

print(time.perf_counter())

## 01. Arrays 생성

In [ ]:
# Numpy 배열 생성하기

# rank 1 array 생성 ==> 익숙해지기 전까지는 사용하지 마라.
a = np.array([1, 2, 3])
print(type(a))            # "<class 'numpy.ndarray'>"
print(a.shape)            # "(3,)"
print(a[0], a[1], a[2])   # "1 2 3"

In [ ]:
# 값 변경
a[0] = 5
print(a)                  # "[5, 2, 3]"

In [ ]:
# rank 2 array 생성 ==> rank 1 array도 이렇게 사용하라.
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(b.shape)                     # "(2, 3)" (* 주의: 3x2 행렬)
print(b[0, 0], b[0, 1], b[1, 0])   # "1 2 4"
print(b)

### reshape

 중요.!!

In [ ]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(b)

In [ ]:
test = np.zeros((2, 4, 3))

In [ ]:
test.reshape(1,4,-1)

In [ ]:
c = np.reshape(b, (3, 2))
print(c.shape) 
print(c)

In [ ]:
b.reshape(3,-1)

In [ ]:
# 64 * 64 * 3
arr = np.zeros((64, 64, 3))
print(arr.shape)
print(arr)


In [ ]:
b = arr.reshape(64 * 64, 3) 
print(b.shape)


In [ ]:
# -1
c = arr.reshape(16, 16, -1) 
print(c.shape) 
# (64 * 64 * 3) / (16 * 16) = 48이므로 배열의 세 번째 차원의 크기는 48이 됩니다.
print(c)

### reshape 연습 : MNIST

In [ ]:
import matplotlib.pylab as plt

MNIST sample 100 28x28 dense.CSV 파일을 엑셀로 열어서 한번 살펴보자~!

In [ ]:
# MNIST 샘플 데이터를 불러오기
mnist = np.genfromtxt("MNIST sample 100 28x28 dense.CSV", delimiter=",", skip_header=True)
print(type(mnist))
print(mnist.shape)
print(mnist)

이 형태는 정리(전처리)가 잘 된 데이터 셋 이다. <br>
첫번째 칼럼은 Label 이다. <br>
각 행이 하나의 이미지 파일의 픽셀값을 일렬로 만들어 놓은 것.

In [ ]:
mnist_labels = mnist[:,0]  #첫 칼럼은 레이블로 모아두고
mnist_pixels = mnist[:,1:] #나머지 칼럼(픽셀값들)을 따로 저장.

print(mnist_pixels)

In [ ]:
# 원본 이미지 형태로 픽셀을 reshape하여  mnist_pixels2에 담자.
mnist_pixels2 = mnist_pixels.reshape([-1, 28,28])

In [ ]:
# 특정 이미지의 픽셀값을 진짜 이미지로 나타내보자.
image_no = 8
print(mnist_labels[image_no])
plt.imshow(mnist_pixels2[image_no, :, :])

In [ ]:
# 전체 다 가져올 거라면 2,3차원 생략 가능
plt.imshow(mnist_pixels2[19])

보통 CSV 파일은 Pandas로 불러와서 계산을 위해서 Numpy로 변환해서 진행합니다.

### 여러가지 array 생성함수

In [ ]:
# Numpy는 배열을 생성하는 다양한 함수를 제공합니다.

# 0으로 채워진 array 생성
a = np.zeros((2, 2))
print(a)              # "[[ 0.  0.]
                      #   [ 0.  0.]]"

In [ ]:
# 1로 채워진 array 생성
b = np.ones((1, 2))
print(b)              # "[[ 1.  1.]]"

In [ ]:
# 특정 값으로 채워진 array 생성
c = np.full((2, 2), 7.)  
print(c)               # "[[ 7.  7.]
                       #   [ 7.  7.]]"

In [ ]:
# 2x2 단위 행렬(identity matrix) 생성
d = np.eye(2)
print(d)              # "[[ 1.  0.]
                      #   [ 0.  1.]]"

In [ ]:
# 랜덤값으로 채운 array 생성
e = np.random.random((2, 2))
print(e)

Random number 설명

https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html

In [ ]:
# seed 값을 지정하면 항상 동일한 값으로 샘플링 됨.
np.random.seed(1102)  # 값이 동일하면, 컴퓨터와 상관없이 동일한 샘플링
e = np.random.random((2, 2))
print(e)

### 실습 : Arrays 생성

In [ ]:
a = [1, 2, 3, 4, 5, 6]

# 1) a를 가지고 numpy array np_01을 생성하시오


# 2) np_01의 shape를 확인하시오.


# 3) np_01의 shape를 (6, 1)로 변환하여 np_02에 넣으세요. 


# 4) np_01의 shape를 (1, 6)로 변환하여 np_03에 넣으세요. 


# np_01의 shape를 (-1, 2)로 변환하여 np_04에 넣으세요. 


# np_01, np_02, np_03, np_04의 모양을 출력하시고 shape와 실제 값의 모양을 확인하세요. 


# 랜덤값으로 채운 (28, 28) numpy array를 생성하여 np_sample 변수에 담으세요.




## 02. Array Indexing - Slice

In [ ]:
import numpy as np
score_2d = np.array([[78,91,84,89,93,65]
                    ,[82,87,96,79,91,73]])

In [ ]:
score_2d[0] >= 90

In [ ]:
# array[row][column]
score_2d[0][score_2d[0] >= 90]

In [ ]:
# array[row, column]
score_2d[0,score_2d[0] >= 90]

In [ ]:
score_2d[1][score_2d[1] >= 90]

In [ ]:
# 다음의 shape을 가지는 array 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# shape (3, 4) - 4x3 행렬
a

In [ ]:
# Slice를 이용하여 하위 배열 잘라내기.
# [[2 3]
#  [6 7]]

# ?에 올 내용은?
b = a[?, ?]  
print(b)

In [ ]:
# 배열의 조각을 수정하면 원래 배열이 수정됩니다.
print(a[0, 1])   # "2"
b[0, 0] = 77     # b[0, 0] = a[0, 1]
print(a[0, 1])   # "77"

In [ ]:
b_copy = a[0:2,0:2].copy() # 진짜 복사가 된다.
print(b_copy)

In [ ]:
# 다음의 shape을 가지는 array 생성
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 데이터에 액세스하는 두 가지 방법.

# 행
# 1. 정수 인덱스와 슬라이스를 섞으면 더 낮은 순위의 배열이 생성됩니다. 
row_r1 = a[1, :]             # Rank 1
print(row_r1, row_r1.shape)  # "[5 6 7 8] (4,)"

In [ ]:
# 2. 슬라이스만 사용하면 원래 배열과 동일한 순위의 배열이 생성됩니다.
row_r2 = a[1:2, :]           # Rank 2
print(row_r2, row_r2.shape)  # "[[5 6 7 8]] (1, 4)"

In [ ]:
# 열
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)  # "[ 2  6 10] (3,)"

In [ ]:
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)  # "[[ 2]
                             #   [ 6]
                             #   [10]] (3, 1)"

In [ ]:
# Integer array indexing
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2]]
print(b)

In [ ]:
# 실행하기 전에 아래 문장의 결과를 예상해보세요!
print(a[[0, 1, 2], [0, 1, 0]])   

In [ ]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# 같은 위치 데이터를 여러번 사용할 수 있음
# "[2 2]"
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))  

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)  # "array([[ 1,  2,  3],
          #         [ 4,  5,  6],
          #         [ 7,  8,  9],
          #         [10, 11, 12]])"



In [ ]:
# element 선택 방식
b = np.arange(4)
c = np.array([0, 2, 0, 1])
print(b)
print(c)
print(a[b, c])  # "[ 1  6  7 11]"

In [ ]:
# 선택된 모든 element를 변경
a[b, c] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
# Boolean array indexing

a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)      # "[[False False]
                     #   [ True  True]
                     #   [ True  True]]"

In [ ]:
print(a[bool_idx])  # "[3 4 5 6]"
print(a[a > 2])     # "[3 4 5 6]"

### 실습 : Arrays Indexing

In [ ]:
# 1) 다음의 shape을 가지는 numpy array를 생성하여 np_arr 변수에 담으세요
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]


# 2) np_arr의 shape를 확인하세요. 


# 3) np_arr의 3행의 데이터를 1차원 배열로 출력하세요.
# [7 8 9]


# 4) np_arr의 2열의 데이터를 1차원 배열로 출력하세요.
# [2 5 8 11]


# 5) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.



# 6) 위의 실습에서 선택된 element 값을 모두 2배로 만드세요.



# 7) np_arr을 출력해 봅니다.



# np_arr의 element중에 3의 배수인 element만 찾습니다. (3의 배수 찾는 법: x % 3 == 0)




## 03. Data 변환

In [ ]:
x = np.array([1, 2])
print(x.dtype)             # "int64"

x = np.array([1.0, 2.0])
print(x.dtype)             #"float64"

In [ ]:
x = np.array([1.9, 2.0], dtype=np.int32)   # 강제로 데이터 형식 지정
print(x.dtype)                         # "int32"
print(x)

int32 : –2,147,483,648 ~ 2,147,483,647 <br>
int64 : –9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807

In [ ]:
# Numpy Array
x = np.array([1, 2])
print(type(x))             # <class ‘numpy.ndarray’>

In [ ]:
# numpy.ndarray to list
y = x.tolist()     # 종종 쓰인다. 
print(y)               # [1, 2]
print(type(y))             # <class ‘list’>

## 04. Array Math

함수 그대로 사용하기. 

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [ ]:
# array 더하기
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

In [ ]:
# array 빼기
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

In [ ]:
# array 곱하기
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

In [ ]:
# array 나누기
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# array 제곱근
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# array 제곱
print(x ** 2)
print(np.power(x, 2))


In [ ]:
# List와 다른점
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight * height ** 2
#TypeError: unsupported operand type(s) for **: 'list' and 'int'


In [ ]:
np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height ** 2
#array([ 21.852, 20.975, 21.75 , 24.747, 21.441])

In [ ]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

python_list + python_list
# [1, 2, 3, 1, 2, 3]

In [ ]:
numpy_array + numpy_array
# array([2, 4, 6])

### 행렬 곱

In [ ]:
# 행렬곱

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
# (1, 2) * (1, 2), 219
print(9 * 11 + 10 * 12)
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
# (2, 2) * (1, 2), rank 2 array
print("(1, 1): %d" % (1 * 9 + 2 * 10))
print("(1, 2): %d" % (3 * 9 + 4 * 10))
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# (2, 2) * (2, 2), rank 2 array
# [[19 22]
#  [43 50]]
print("(1, 1): %d" % (1 * 5 + 2 * 7))
print("(1, 2): %d" % (1 * 6 + 2 * 8))
print("(2, 1): %d" % (3 * 5 + 4 * 7))
print("(2, 2): %d" % (3 * 6 + 4 * 8))
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
x = np.array([[1, 2], [3, 4]])

# 합산
print(np.sum(x))          # "10"

# 열 합산
print(np.sum(x, axis=0))  # "[4 6]"

# 행 합산
print(np.sum(x, axis=1))  # "[3 7]"

In [ ]:
# 전치행렬

x= np.array([1, 2, 3, 4], ndmin=2)
print(x.T)

In [ ]:
x = np.array([[1, 2], [3, 4]])
print(x)    # "[[1 2]
            #   [3 4]]"

print(x.T)  # "[[1 3]
            #   [2 4]]"

In [ ]:
x = np.array([1, 2, 3, 4], ndmin=2) # ndmin 없이 해보기, 없으면 1차원 array으로 만들어진다. 전치행렬이 동작하지 않는다.
print(x)   	    # "[[1 2 3 4]]"
print(x.shape)  # (1, 4)

# 전치 행렬
print(x.T)  # "[[1]
            #   [2]
            #   [3]
            #   [4]]”
            
# rank 1 에서는 변화가 없음
v = np.array([1,2,3])
print(v)    # "[1 2 3]"
print(v.T)  # "[1 2 3]"

### 실습 : 변환과 연산

In [ ]:
# 1) 랜덤값으로 채운 (4, 3) numpy array를 생성하여 rand 변수에 담으세요.
 

# 2) rand를 출력하세요.


# 3) rand를 열 방향으로 합산하세요.


# 4) rand를 행 방향으로 합산하세요.


# 5) rand의 전치 행렬을 출력하세요.


## 06. Shuffle, Sampling, Split

### shuffle

In [ ]:
data = np.genfromtxt("./Graduate_apply.csv", delimiter=",", names=True)

print(data[0:10])

In [ ]:
# Shuffle
np.random.shuffle(data)

print(data[0:10])

### sampling

[여기참고](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.choice.html)

In [ ]:
?np.random.choice
np.random.choice(data, 4)

In [ ]:
# 복원추출 : 한번 뽑은 것을 다시 뽑을 수 있는 추출
np.random.choice(np.array([0,1,2,3,4,5,6,7,8,9]), 4)

In [ ]:
# 비복원추출 : 한번 뽑은 것을 다시 뽑을 수 없는 추출
np.random.choice(np.array([0,1,2,3,4,5,6,7,8,9]), 4, replace = False)

### split

In [ ]:
# Split
s1, s2, s3, s4 = data[:100], data[100:200], data[200:300], data[300:]
print(len(s1))
print(s1)
print(len(s2))
print(len(s3))
print(len(s4))

### 실습 : Shuffle, Sampling, Split

In [ ]:
# 1) ./Graduate_apply.csv 파일을 읽어서 apply 변수에 담으세요. 


# 2) apply의 element 갯수를 확인하세요. (400)


# 3) apply의 데이터 중 0 ~ 300 까지의 행은 train 변수에, 300 ~ 마지막 까지의 행은 test 변수에 담으세요.


# 4) train에 담겨있는 데이터를 suffle 한 후 상위 5개 데이터를 조회하시오.



## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the <a href="http://docs.scipy.org/doc/numpy/reference/">numpy reference</a> to find out much more about numpy.